"use strict";
const uxp=require("uxp"),{entrypoints}=uxp,premiere=require("premierepro");
entrypoints.setup({panels:{velvetPremiereBridge:{show(){},hide(){}}}});
const JSONRPC_VERSION="2.0",ERROR_METHOD_NOT_FOUND=-32601,ERROR_HOST_SCRIPT=-32004;
const url=globalThis.__ADOBEPY_BROKER_URL,token=globalThis.__ADOBEPY_TOKEN,target=globalThis.__ADOBEPY_TARGET||"default";
let socket=null,reconnectTimer=null,reconnectDelayMs=1000;
const scalar=v=>v==null?null:(typeof v==="object"&&v.value!=null?v.value:String(v));
const hostVersion=()=>String(premiere.version||(uxp.host&&uxp.host.version)||"unknown");
async function activeProjectInfo(){const p=await premiere.Project.getActiveProject();if(!p)return null;let s=null;try{s=await p.getActiveSequence();}catch(_){}return {guid:scalar(p.guid),name:scalar(p.name),path:scalar(p.path),activeSequence:s?{guid:scalar(s.guid||s.id||s.sequenceID),name:scalar(s.name)}:null};}
function closeOptions(){const o=new premiere.CloseProjectOptions();o.setPromptIfDirty(false);o.setShowCancelButton(false);o.setSaveWorkspace(false);o.setIsAppBeingPreparedToQuit(false);return o;}
async function acceptanceTemporaryCycle(){let stage="getTemporaryFolder",p=null,closed=false,fileName=null;try{const folder=await uxp.storage.localFileSystem.getTemporaryFolder();const base=String(folder&&folder.nativePath||"").replace(/[\\\/]+$/,"");if(!base)throw new Error("UXP temporary folder has no nativePath");fileName="VelvetOS-Premiere-Acceptance-"+Date.now()+".prproj";const sep=base.includes("\\")?"\\":"/";const filePath=base+sep+fileName;stage="createProject";p=await premiere.Project.createProject(filePath);if(!p)throw new Error("Premiere did not create the temporary project");const created={guid:scalar(p.guid),name:scalar(p.name),path:scalar(p.path)};stage="getActiveProject";const active=await premiere.Project.getActiveProject();const activeAfterCreate=active?{guid:scalar(active.guid),name:scalar(active.name),path:scalar(active.path)}:null;stage="closeProject";closed=Boolean(await p.close(closeOptions()));if(!closed)throw new Error("Premiere returned close=false");stage="deleteTemporaryFile";const entry=await uxp.storage.localFileSystem.getEntryWithUrl("plugin-temp:/"+fileName);await entry.delete();return {created,activeAfterCreate,closed,tempFileDeleted:true,tempLocation:"plugin-temp"};}catch(e){if(p&&!closed){try{await p.close(closeOptions());}catch(_){}}if(fileName){try{const entry=await uxp.storage.localFileSystem.getEntryWithUrl("plugin-temp:/"+fileName);await entry.delete();}catch(_){}}const msg=e instanceof Error?e.message:String(e);throw new Error(stage+": "+msg);}}
function capabilities(){return {host:"premiere",bridgeKind:"uxp",bridgeVersion:"0.1.3",hostVersion:hostVersion(),namespaces:["app","project"],features:["reconnect","readOnly","controlledTemporaryWrite"],methods:{app:["getVersion","getWriteSupport"],project:["getActive","acceptTemporaryCycle"]}};}
async function dispatch(r){if(r.namespace==="app"&&r.method==="getVersion")return hostVersion();if(r.namespace==="app"&&r.method==="getWriteSupport")return {createProject:typeof premiere.Project.createProject,closeProjectOptions:typeof premiere.CloseProjectOptions,tempStorage:"plugin-temp"};if(r.namespace==="project"&&r.method==="getActive")return await activeProjectInfo();if(r.namespace==="project"&&r.method==="acceptTemporaryCycle")return await acceptanceTemporaryCycle();const e=new Error("unsupported method "+r.namespace+"."+r.method);e.code=ERROR_METHOD_NOT_FOUND;throw e;}
function hostError(id,e){return {jsonrpc:JSONRPC_VERSION,id,error:{code:Number.isInteger(e&&e.code)?e.code:ERROR_HOST_SCRIPT,message:e instanceof Error?e.message:String(e)}};}
function send(m){if(socket&&socket.readyState===WebSocket.OPEN)socket.send(JSON.stringify(m));}
function scheduleReconnect(){if(reconnectTimer)return;reconnectTimer=setTimeout(()=>{reconnectTimer=null;connect();},reconnectDelayMs);reconnectDelayMs=Math.min(reconnectDelayMs*2,15000);}
function connect(){if(typeof url!=="string"||!url||typeof token!=="string"||!token)return;try{socket=new WebSocket(url);}catch(e){scheduleReconnect();return;}socket.addEventListener("open",()=>{reconnectDelayMs=1000;send({type:"hello",token,target,capabilities:capabilities()});});socket.addEventListener("message",async ev=>{let m;try{m=JSON.parse(ev.data);}catch(_){return;}if(!m||m.type!=="request"||!m.request)return;const r=m.request;try{const result=await dispatch(r);send({type:"response",response:{jsonrpc:JSONRPC_VERSION,id:r.id,result:result===undefined?null:result}});}catch(e){send({type:"error",error:hostError(r.id,e)});}});socket.addEventListener("close",scheduleReconnect);socket.addEventListener("error",()=>{try{socket.close();}catch(_){}});}
connect();