#!/usr/bin/env python3
"""Hashed sensor lock files stay consistent with requirements-sensors.txt and CI.

- requirements-sensors.py311.lock / .py312.lock exist, were generated by
  pip-compile for the matching Python, and pin EVERY package with >=1 sha256 hash;
- every pin in requirements-sensors.txt that applies to that Python appears in
  the lock at the same version (lock may add indirect deps; they are hashed too);
- every workflow that installs the sensor runtime uses
  `--require-hashes -r requirements-sensors.py3XX.lock` matching its
  setup-python version and never installs requirements-sensors.txt directly.
Regenerate with scripts/regen-sensor-locks.sh. Stdlib only, read-only.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NAME = "sensor-locks"
LOCKS = {"3.11": "requirements-sensors.py311.lock", "3.12": "requirements-sensors.py312.lock"}
PIN_RE = re.compile(r'^([A-Za-z0-9_.\-]+)==([^\s;\\]+)\s*(?:;\s*([^\\#]+?))?\s*(?:\\|#.*)?$')
MARKER_RE = re.compile(r'^python_version\s*(<|<=|>=|>|==)\s*"(\d+)\.(\d+)"$')


def fail(msg: str) -> None:
    print(f"FAIL {NAME}: {msg}", file=sys.stderr)
    raise SystemExit(1)


def norm(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def marker_applies(marker: str | None, py: str) -> bool:
    if not marker:
        return True
    m = MARKER_RE.match(marker.strip())
    if not m:
        raise ValueError(f"unsupported marker {marker!r}")
    op, a, b = m.group(1), int(m.group(2)), int(m.group(3))
    cur = tuple(int(x) for x in py.split("."))
    ref = (a, b)
    return {"<": cur < ref, "<=": cur <= ref, ">=": cur >= ref, ">": cur > ref, "==": cur == ref}[op]


def parse_input(text: str, py: str) -> dict[str, str]:
    out: dict[str, str] = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        m = PIN_RE.match(line)
        if not m:
            raise ValueError(f"unparsed requirement line: {line!r}")
        if marker_applies(m.group(3), py):
            out[norm(m.group(1))] = m.group(2)
    return out


def parse_lock(text: str) -> dict[str, dict]:
    pins: dict[str, dict] = {}
    current = None
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("--hash="):
            if current is None:
                raise ValueError("hash line before any pin")
            if not re.fullmatch(r"--hash=sha256:[0-9a-f]{64}\s*\\?", line):
                raise ValueError(f"bad hash line: {line!r}")
            pins[current]["hashes"] += 1
            continue
        m = PIN_RE.match(line)
        if not m:
            raise ValueError(f"unparsed lock line: {line!r}")
        current = norm(m.group(1))
        pins[current] = {"version": m.group(2), "hashes": 0}
    return pins


def lock_problems(py: str, input_text: str, lock_text: str) -> list[str]:
    p: list[str] = []
    if f"autogenerated by pip-compile with Python {py}" not in lock_text:
        p.append(f"{LOCKS[py]} must be generated by pip-compile with Python {py}")
    try:
        want = parse_input(input_text, py)
        have = parse_lock(lock_text)
    except ValueError as exc:
        return p + [str(exc)]
    for name, meta in have.items():
        if meta["hashes"] < 1:
            p.append(f"{LOCKS[py]}: {name} has no sha256 hash")
    for name, ver in want.items():
        if name not in have:
            p.append(f"{LOCKS[py]} missing {name}=={ver} from requirements-sensors.txt")
        elif have[name]["version"] != ver:
            p.append(f"{LOCKS[py]} pins {name}=={have[name]['version']} but requirements-sensors.txt says {ver}")
    return p


def workflow_problems(rel: str, text: str) -> list[str]:
    p: list[str] = []
    if "requirements-sensors" not in text:
        return p
    if re.search(r"-r\s+requirements-sensors\.txt", text):
        p.append(f"{rel} installs requirements-sensors.txt directly; use the hashed lock")
    pyv = re.findall(r"python-version:\s*['\"]?(\d+\.\d+)", text)
    for m in re.finditer(r"pip install[^\n]*-r\s+(requirements-sensors\.py(\d)(\d+)\.lock)", text):
        line = text[text.rfind("\n", 0, m.start()) + 1 : text.find("\n", m.end())]
        if "--require-hashes" not in line:
            p.append(f"{rel} must install {m.group(1)} with --require-hashes")
        lock_py = f"{m.group(2)}.{m.group(3)}"
        if pyv and lock_py not in pyv:
            p.append(f"{rel} installs {m.group(1)} but sets up Python {pyv}")
    return p


def main() -> int:
    input_text = (ROOT / "requirements-sensors.txt").read_text(encoding="utf-8")
    probs: list[str] = []
    counts = {}
    for py, rel in LOCKS.items():
        path = ROOT / rel
        if not path.is_file():
            fail(f"missing {rel}; run scripts/regen-sensor-locks.sh")
        lock_text = path.read_text(encoding="utf-8")
        probs += lock_problems(py, input_text, lock_text)
        counts[py] = len(parse_lock(lock_text)) if not probs else 0
    installers = 0
    for wf in sorted((ROOT / ".github" / "workflows").glob("*.y*ml")):
        text = wf.read_text(encoding="utf-8")
        rel = str(wf.relative_to(ROOT))
        if "requirements-sensors" in text:
            installers += 1
        probs += workflow_problems(rel, text)
    if probs:
        for x in probs:
            print(f"FAIL {NAME}: {x}", file=sys.stderr)
        return 1

    # Negative controls.
    lock311 = (ROOT / LOCKS["3.11"]).read_text(encoding="utf-8")
    controls = [
        ("drifted version", lock_problems("3.11", input_text.replace("Pillow==12.3.0", "Pillow==12.2.0"), lock311)),
        ("missing hash", lock_problems("3.11", input_text, re.sub(r"\n\s+--hash=sha256:[0-9a-f]{64}(?: \\)?", "", lock311))),
        ("wrong python", lock_problems("3.12", input_text, lock311)),
        ("txt install", workflow_problems("x.yml", "python-version: '3.11'\nrun: pip install -r requirements-sensors.txt")),
        ("no hashes flag", workflow_problems("x.yml", "python-version: '3.11'\nrun: pip install -r requirements-sensors.py311.lock")),
        ("version mismatch", workflow_problems("x.yml", "python-version: '3.12'\nrun: pip install --require-hashes -r requirements-sensors.py311.lock")),
    ]
    for label, found in controls:
        if not found:
            fail(f"negative control not caught: {label}")
    print(
        f"OK {NAME} py311={counts['3.11']} py312={counts['3.12']} pins hashed, match requirements-sensors.txt; "
        f"workflows={installers} install --require-hashes; negative_controls={len(controls)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
