#!/usr/bin/env python3
"""Phase 11: production-independent CAD / DfAM / Orca offline slicer validation.

This adapter never modifies native profiles, does not connect to any printer
and never uploads or starts a print. Passing means an *offline capability
fixture*, not production approval or firmware safety certification.
"""
from __future__ import annotations

import argparse
import copy
import hashlib
import json
import math
import pathlib
import re
import subprocess
import sys
import tempfile
from typing import Any

ROOT=pathlib.Path(__file__).resolve().parents[1]
BASE=ROOT/"docs"/"implementation"/"ai-3d-modeling-engineering-core"
CONFIG=BASE/"dfam-slicer-v1.json"
SOURCE=ROOT/"packages"/"vfharness"/"state"/"cad-engine-stack-20260927"/"geometry-ir-sample.json"
CAD=ROOT/"scripts"/"vf_cad_stack.py"
BRIDGE=ROOT/"scripts"/"vf_cad.py"
PROBE=ROOT/"scripts"/"ai3d_exact_cad_probe.py"
DEFAULT_EVIDENCE=BASE/"evidence"/"phase11-dfam-slicer-acceptance-20261008.json"

sys.path.insert(0,str(ROOT/"scripts"))
import vf_cad_stack  # noqa:E402


def load_json(path: pathlib.Path) -> dict[str,Any]:
    with path.open("r",encoding="utf-8-sig") as f:
        obj=json.load(f)
    if not isinstance(obj,dict):
        raise ValueError(f"{path}: not a JSON object")
    return obj


def digest(path: pathlib.Path)->str:
    h=hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda:f.read(1024*1024),b""):
            h.update(chunk)
    return h.hexdigest()


def file_receipt(path: pathlib.Path)->dict[str,Any]:
    assert path.is_file() and path.stat().st_size>0,f"artifact missing/empty: {path}"
    return {"name":path.name,"bytes":path.stat().st_size,"sha256":digest(path)}


def invoke(command:list[str], *, expected:int|None=0, timeout:int=90)->subprocess.CompletedProcess[str]:
    p=subprocess.run(command,cwd=ROOT,timeout=timeout,
        capture_output=True,text=True,encoding="utf-8",errors="replace")
    if expected is not None and p.returncode != expected:
        raise AssertionError(
            f"unexpected return code={p.returncode}, expected={expected}: {' '.join(command)}"
            f"\nstdout-tail={p.stdout[-1800:]}\nstderr-tail={p.stderr[-1800:]}"
        )
    return p


def json_stream(stdout:str)->list[dict[str,Any]]:
    decoder=json.JSONDecoder()
    objs=[]
    idx=0
    while idx<len(stdout):
        while idx<len(stdout) and stdout[idx].isspace():
            idx+=1
        if idx==len(stdout):
            break
        item,idx=decoder.raw_decode(stdout,idx)
        if not isinstance(item,dict):
            raise ValueError("unexpected non-JSON-object in canonical wrapper stream")
        objs.append(item)
    return objs


def close_vec(actual:list[float],target:list[float],tol:float,label:str)->None:
    assert len(actual)==len(target),(label,actual,target)
    for x,y in zip(actual,target):
        assert math.isfinite(float(x)) and abs(float(x)-float(y))<=tol,(label,actual,target)


def profiles()->dict[str,pathlib.Path]:
    p=invoke([sys.executable,str(BRIDGE),"profiles"])
    j=json.loads(p.stdout)
    assert j["status"]=="PASS"
    result={key:pathlib.Path(path) for key,path in j["profiles"].items()}
    assert {"c5","h2d","ecc2","u1","c5pro"}<=set(result)
    assert all(x.is_file() for x in result.values())
    return result


def immutable_profile_sources(wrapper:pathlib.Path)->list[pathlib.Path]:
    j=load_json(wrapper)
    paths=[wrapper,pathlib.Path(j["native_config"])]
    paths.extend(pathlib.Path(x) for x in j["native_settings"])
    paths.extend(pathlib.Path(x) for x in j["native_filaments"])
    unique={str(p.resolve()).lower():p.resolve() for p in paths}
    assert all(p.is_file() for p in unique.values())
    return sorted(unique.values(),key=lambda p:str(p).lower())


def machine_limits(wrapper:pathlib.Path)->dict[str,Any]:
    j=load_json(wrapper)
    return {
        "name":j["machine"]["name"],
        "bed_xy":j["machine"]["bed_size_mm"],
        "max_z":j["machine"]["z_height_mm"],
        "native_config":j["native_config"],
        "nozzle_temperature_declared":j["filament"]["nozzle_temp_c"],
        "filament":j["filament"]["type"],
    }


def fits_bed(source_xyz:list[float],bounds:dict[str,Any])->bool:
    return (
        len(source_xyz)==3 and
        all(isinstance(v,(int,float)) and not isinstance(v,bool) and math.isfinite(v) and v>0 for v in source_xyz)
        and source_xyz[0] <= float(bounds["bed_xy"][0])
        and source_xyz[1] <= float(bounds["bed_xy"][1])
        and source_xyz[2] <= float(bounds["max_z"])
    )


def gcode_evidence(path:pathlib.Path,expected_z:float,max_delta:float)->dict[str,Any]:
    with path.open("r",encoding="utf-8",errors="replace") as f:
        header="".join([f.readline() for _ in range(10)])
    match_version=re.search(r"; generated by OrcaSlicer ([0-9.]+)",header)
    match_layers=re.search(r"; total layer number:\s*(\d+)",header)
    match_z=re.search(r"; max_z_height:\s*(\d+(?:\.\d+)?)",header)
    assert match_version and match_layers and match_z, "real Orca G-code header fields missing"
    version=match_version.group(1)
    layers=int(match_layers.group(1))
    z=float(match_z.group(1))
    assert version=="2.4.2",("runtime version unexpectedly changed",version)
    assert layers>1 and z>0
    assert abs(z-expected_z)<=max_delta,("sliced max-z differs from CAD geometry",z,expected_z)
    return {
        "generator":"OrcaSlicer",
        "reported_version":version,
        "reported_layer_count":layers,
        "reported_max_z_mm":z,
        "source_cad_max_z_mm":expected_z,
        "max_height_delta_mm":abs(z-expected_z),
        "artifact":file_receipt(path),
    }


def slicer_call(mesh:pathlib.Path,printer:str,target:pathlib.Path)->dict[str,Any]:
    assert not target.exists(),f"refusing to overwrite: {target}"
    process=invoke([
        sys.executable,str(BRIDGE),"slice",
        "--input",str(mesh),
        "--printer",printer,
        "--output",str(target),
        "--execute",
    ],expected=None,timeout=90)
    objects=json_stream(process.stdout)
    assert len(objects)==2,(printer,mesh.suffix,len(objects),process.stderr[-1000:])
    slicer_plan,validation=objects
    assert slicer_plan["backend"]=="orcaslicer"
    assert slicer_plan["returncode"]==0
    assert slicer_plan["dry_run"] is False
    assert pathlib.Path(slicer_plan["generated"]["path"]).resolve()==target.resolve()
    assert target.is_file(),target
    assert validation["path"]==str(target)
    return {
        "bridge_returncode":process.returncode,
        "slicer_returncode":slicer_plan["returncode"],
        "validation_ok":validation["ok"],
        "validation_errors":validation["errors"],
        "validation_warnings":validation["warnings"],
        "stats":validation["stats"],
        "command_backend":"orcaslicer",
        "input_extension":mesh.suffix,
        "artifact":file_receipt(target),
    }


def run_dfam(mesh:pathlib.Path)->dict[str,Any]:
    p=invoke([sys.executable,str(BRIDGE),"dfam","--input",str(mesh)])
    j=json.loads(p.stdout)
    assert j.get("partial") is False,("DFAM reports partial",j.get("partial"))
    assert "support_volume" in j
    assert j["support_volume"]["part_volume_mm3"]>0
    return {
        "partial":False,
        "source_stl_sha256":digest(mesh),
        "support_estimate":j["support_volume"],
        "other_sections":sorted(k for k in j if k!="support_volume"),
        "caveat":"coarse geometric support estimate; not structural/printability approval",
    }


def injected_out_of_bounds(gcode:pathlib.Path,profile:pathlib.Path,scratch:pathlib.Path)->str:
    # Synthetic negative fixture: this G-code is never transmitted to a printer.
    src=gcode.read_text(encoding="utf-8",errors="replace")
    poisoned=src.replace(
        "; EXECUTABLE_BLOCK_START",
        "; EXECUTABLE_BLOCK_START\nG1 X9999 Y9999 Z0.2 F3000 ; AI3D_OFFLINE_NEGATIVE_ONLY",
        1,
    )
    assert poisoned != src
    scratch.write_text(poisoned,encoding="utf-8",newline="\n")
    text2cad_root=profile.parents[2]/"tools"/"text-to-cad"
    tool=text2cad_root/"skills"/"gcode"/"scripts"/"gcode_tool.py"
    runtime=text2cad_root/".venv"/"Scripts"/"python.exe"
    assert tool.is_file() and runtime.is_file()
    p=invoke([
        str(runtime),str(tool),"validate",
        "--gcode",str(scratch),
        "--profile",str(profile),
        "--json",
    ],expected=None,timeout=20)
    assert p.returncode!=0,"unsafe out-of-bounds injection was accepted"
    obj=json.loads(p.stdout)
    assert obj["ok"] is False
    assert any("outside" in msg.lower() and "motion range" in msg.lower()
               for msg in obj["errors"]),obj["errors"]
    return "BLOCKED"


def unmeshable_step_blocked(step:pathlib.Path,profile:str,out:pathlib.Path)->str:
    p=invoke([sys.executable,str(BRIDGE),"slice","--input",str(step),
      "--printer",profile,"--output",str(out)],expected=None,timeout=15)
    assert p.returncode!=0,"STEP directly accepted by FDM slicing"
    assert not out.exists()
    return "BLOCKED"


def main()->int:
    parser=argparse.ArgumentParser()
    parser.add_argument("--artifacts-root",type=pathlib.Path)
    parser.add_argument("--evidence-out",type=pathlib.Path,default=DEFAULT_EVIDENCE)
    args=parser.parse_args()

    config=load_json(CONFIG)
    assert config["schema"]=="velvetos.ai3d.dfam-slicer.v1"
    assert config["non_authoritative_staging"] is True
    assert config["existing_slicer_authority"]=="scripts/vf_cad.py"
    assert config["authority"]=="packages/vfprod/FABRICATION-ROUTER.md"
    assert all(value is False for value in config["prohibitions"].values())

    printer_profiles=profiles()
    tracked_paths={}
    for name in ("c5","h2d"):
        for path in immutable_profile_sources(printer_profiles[name]):
            tracked_paths[str(path)]=digest(path)

    temp=None
    if args.artifacts_root is None:
        temp=tempfile.TemporaryDirectory(prefix="ai3d-phase11-")
        root=pathlib.Path(temp.name)
    else:
        root=args.artifacts_root.resolve()
        assert not root.exists(),f"Phase11 artifacts root exists, refusing overwrite: {root}"
        root.mkdir(parents=True,exist_ok=False)
    try:
        exact=root/"cad"
        build=invoke([
            sys.executable,str(CAD),"build",
            "--input",str(SOURCE),
            "--engine","build123d",
            "--formats","step,stl,3mf",
            "--out-dir",str(exact),
        ],timeout=90)
        build_json=json.loads(build.stdout)
        assert build_json["status"]=="PASS"
        assert build_json["printer_actions_allowed"] is False
        assert set(build_json["artifacts"])=={"model.step","model.stl","model.3mf"}
        files={ext:exact/f"model.{ext}" for ext in ("step","stl","3mf")}
        geometry_probe=invoke([
            str(vf_cad_stack.runtime_paths()["build123d"]),
            str(PROBE),"--artifact-dir",str(exact),"--skip-bd-warehouse",
        ],timeout=90)
        cad=json.loads(geometry_probe.stdout)["artifacts"]
        sizes=list(cad["step"]["bbox_size"])
        close_vec(cad["stl"]["bbox_size"],sizes,0.002,"STEP->STL")
        close_vec(cad["3mf"]["shapes"][0]["bbox_size"],sizes,0.002,"STEP->3MF")
        assert cad["stl"]["mesh_watertight"] is True
        assert cad["stl"]["mesh_body_count"]==1
        assert cad["step"]["volume"]>0
        assert abs(cad["step"]["volume"]-cad["stl"]["mesh_volume"])/cad["step"]["volume"]<0.01
        bounds=machine_limits(printer_profiles["c5"])
        assert fits_bed(sizes,bounds),"model exceeds declared printer envelope"
        assert not fits_bed([999.0,80.0,12.0],bounds),"oversized negative fixture accepted"

        dfam=run_dfam(files["stl"])
        c5_stl=slicer_call(files["stl"],"c5",root/"c5-from-stl.gcode")
        c5_3mf=slicer_call(files["3mf"],"c5",root/"c5-from-3mf.gcode")
        for item in (c5_stl,c5_3mf):
            assert item["bridge_returncode"]==0
            assert item["validation_ok"] is True
            assert not item["validation_errors"]
            assert item["stats"]["extrusion_moves"]>100
            assert item["stats"]["temperature_commands"]>0
        max_dz=float(config["slicer"]["output_acceptance"]["maximum_model_height_delta_mm"])
        gcode_stl=gcode_evidence(root/"c5-from-stl.gcode",sizes[2],max_dz)
        gcode_3mf=gcode_evidence(root/"c5-from-3mf.gcode",sizes[2],max_dz)
        assert gcode_stl["reported_layer_count"]==gcode_3mf["reported_layer_count"]
        assert abs(gcode_stl["reported_max_z_mm"]-gcode_3mf["reported_max_z_mm"])<=0.1

        h2d_profile=printer_profiles["h2d"]
        h2d_machine=load_json(pathlib.Path(load_json(h2d_profile)["native_config"]))
        raw_start=str(h2d_machine.get("machine_start_gcode") or "")
        assert "G1 X270 Y-0.5 F60000" in raw_start, "expected H2D special-motion source not verified"
        h2d=slicer_call(files["stl"],"h2d",root/"h2d-from-stl.gcode")
        assert h2d["slicer_returncode"]==0 and h2d["validation_ok"] is False
        assert h2d["bridge_returncode"]!=0
        assert h2d["validation_errors"],"H2D missing motion-envelope block"
        assert all("Y=-0.5" in e and "outside Y motion range" in e
                   for e in h2d["validation_errors"]),h2d["validation_errors"]
        h2d["status"]="BLOCKED_MOTION_BOUNDS"
        h2d["source_native_profile_has_start_service_move"]=True

        negative={
            "oversized_model_preflight":"BLOCKED",
            "direct_step_input_to_slicer":unmeshable_step_blocked(
                files["step"],"c5",root/"should-not-slice-step.gcode"),
            "injected_out_of_bounds_gcode":injected_out_of_bounds(
                root/"c5-from-stl.gcode",printer_profiles["c5"],root/"bad-motion-gcode.tmp.gcode"),
            "h2d_start_motion_without_bounds_evidence":"BLOCKED",
        }
        (root/"bad-motion-gcode.tmp.gcode").unlink(missing_ok=True)

        tracked_after={path:digest(pathlib.Path(path)) for path in tracked_paths}
        assert tracked_after==tracked_paths,"native profile or wrapper mutated by offline validation"

        evidence={
            "schema":"velvetos.ai3d.phase11-dfam-slicer-acceptance.v1",
            "status":"PASS_BOUNDED_OFFLINE",
            "authority":config["authority"],
            "source_ir":str(SOURCE.relative_to(ROOT)).replace("\\","/"),
            "source_ir_sha256":digest(SOURCE),
            "slicer_runtime":"OrcaSlicer 2.4.2 via existing vf_cad.py/gcode_tool.py",
            "engine":"build123d via existing vf_cad_stack.py",
            "source_geometry":{
                "bbox_mm":sizes,
                "step_volume_mm3":cad["step"]["volume"],
                "stl_volume_mm3":cad["stl"]["mesh_volume"],
                "mesh_watertight":True,
                "single_body":True,
                "reopen_parity":"PASS",
            },
            "cad_artifacts":[file_receipt(p) for p in files.values()],
            "dfam":dfam,
            "verified_offline":{
                "c5_stl":{**c5_stl,**gcode_stl,"status":"PASS_OFFLINE_ONLY"},
                "c5_3mf":{**c5_3mf,**gcode_3mf,"status":"PASS_OFFLINE_ONLY"},
            },
            "quarantined_profiles":{"h2d":h2d},
            "profile_file_sha256_before_after":tracked_paths,
            "native_profiles_unchanged":True,
            "negative_controls":negative,
            "remaining_profiles_not_qualified":config["slicer"]["not_yet_qualified_profiles"],
            "print_release":"NOT_AUTHORIZED",
            "safety":config["prohibitions"],
            "notes":[
                "Offline toolchain capability only, not printer firmware validation or material calibration.",
                "G-code unknown-dialect warnings are preserved; no commands sent to hardware.",
                "H2D machine-start service Y=-0.5 movement remains BLOCKED pending independently verified motion envelope.",
                "Do not assume the G-code is a safe production job based on a local validator PASS.",
            ],
            "artifact_directory":str(root) if args.artifacts_root else "temporary/ephemeral",
        }
        args.evidence_out.parent.mkdir(parents=True,exist_ok=True)
        with args.evidence_out.open("w",encoding="utf-8",newline="\n") as f:
            f.write(json.dumps(evidence,indent=2,ensure_ascii=False)+"\n")
        print(
            "validate_ai3d_phase11_dfam_slicer: PASS "
            f"bbox={sizes} c5_stl_layers={gcode_stl['reported_layer_count']} "
            f"c5_3mf_layers={gcode_3mf['reported_layer_count']} "
            f"h2d=BLOCKED native_profiles=UNCHANGED negatives={len(negative)}"
        )
    finally:
        if temp is not None:
            temp.cleanup()
    return 0


if __name__=="__main__":
    raise SystemExit(main())
