#!/usr/bin/env python3
"""P0 #612 offline QA gate: distinct NEW Mac Qwen task repairs exact-int bug.

The V3 model-generated bytes are quarantined, never runtime-imported or
model-rerun in CI. Read-only source SHA+AST guard, pure bounded subprocess
property suite, original old bug must stay demonstrably detectable.
"""
from __future__ import annotations
import argparse
import ast
import copy
import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile

import vf_office_v2_p0_model_artifact_pr_gate as old_gate

ROOT = Path(__file__).resolve().parent.parent
P2 = ROOT / "docs/implementation/office-v2/phase2"
SOURCE = P2 / "quarantined-agent-sources-2026-10-10/windows_merge_exact_int_v3.py"
EVIDENCE = P2 / "p0-fresh-exact-int-v3-model-result-2026-10-10.json"
SCHEMA = "velvetos.office-v2.p0-exact-int-fresh-task-pr-evidence.v0"
SOURCE_SHA = "0ec526a84d6a814aecbfc586c237ef59044811f920c0d73640cbf24b76e25479"
OLD_SOURCE_SHA = "999f8ae84cbca062a41297b6fadf6703ee69fa8a61e427a8441cd1a169c3b0a0"
MODEL_DIGEST = "7f3251fa6878a78a606bcb3c074283306e5ad2ea411a7774a9dd98a4bc7f2d13"


class Refused(Exception):
    pass


def need(condition, reason):
    if not condition:
        raise Refused(reason)


def verify_source(path=SOURCE):
    p=Path(path)
    need(p.is_file() and not p.is_symlink()
         and p.stat().st_size < 5000,"NEW_EXACT_SOURCE_REQUIRED")
    raw=p.read_bytes()
    need(hashlib.sha256(raw).hexdigest()==SOURCE_SHA,
         "NEW_ORIGINAL_MODEL_CODE_CHANGED")
    try:
        node=ast.parse(raw.decode("utf-8"))
    except (UnicodeError,SyntaxError):
        raise Refused("NEW_MODEL_PYTHON_INVALID")
    need(len(node.body)==1 and isinstance(node.body[0],ast.FunctionDef)
         and node.body[0].name=="merge_windows"
         and not node.body[0].decorator_list,
         "MODEL_CODE_SCOPE_NOT_ALLOWED")
    banned=(ast.Import,ast.ImportFrom,ast.Global,ast.Nonlocal,ast.With,
            ast.AsyncWith,ast.ClassDef,ast.AsyncFunctionDef,ast.Await,
            ast.Yield,ast.YieldFrom)
    permitted_attributes={"append"}
    for entry in ast.walk(node):
        need(not isinstance(entry,banned),"UNREVIEWED_MODEL_AST_FORBIDDEN")
        if isinstance(entry,ast.Attribute):
            need(entry.attr in permitted_attributes,"UNAPPROVED_MODEL_CALL_ATTRIBUTE")
        if isinstance(entry,ast.Name):
            need(not entry.id.startswith("__"),"UNAPPROVED_DUNDER")
    return raw


# Reproduce the exact original independent public property suite seeded in
# PR #659; add subclass-invalid examples that the original hidden QA missed.
# The agent's source is EXECUTED only after static+SHA verification and inside
# a disposable Python subprocess with a small builtins allowlist.
# This is NOT an OS sandbox or network/process isolation for arbitrary code.
QA_RUNNER=r'''
import builtins
import json
import random
import sys
from pathlib import Path
raw=Path(sys.argv[1]).read_bytes()
safe={k:getattr(builtins,k) for k in
      ("int","str","bool","tuple","list","len","type",
       "isinstance","enumerate","sorted","range","max","ValueError")}
scope={"__builtins__":safe,"__name__":"__lab_only__"}
exec(compile(raw,"<original-byte-exact-model-code>","exec"),scope)
merge=scope["merge_windows"]
rng=random.Random(61220261011)
success=0
for iteration in range(256):
    rows=[]
    for index in range(rng.randrange(0,12)):
        lo=rng.randrange(-40,40)
        rows.append((lo,lo+rng.randrange(0,12)))
    rng.shuffle(rows)
    snapshot=rows[:]
    oracle=[]
    for lo,hi in sorted(rows):
        if oracle and lo<=oracle[-1][1]+1:
            oracle[-1]=(oracle[-1][0],max(oracle[-1][1],hi))
        else:
            oracle.append((lo,hi))
    try:
        result=merge(rows)
    except Exception:
        result=None
    if result==oracle and rows==snapshot:
        success+=1
class IntSubclass(int):
    pass
invalid=[[(True,2)],[(1,False)],[(1,2.5)],[[1,2]],
         [(2,1)],[(1,)],[("1",2)],[(1,2,3)],[1],
         [(IntSubclass(1),2)],[(1,IntSubclass(2))]]
rejected=0
for value in invalid:
    try:
        merge(value)
    except ValueError:
        rejected+=1
print(json.dumps({
    "standard_samples":256,
    "standard_oracle_passed":success,
    "invalid_examples":len(invalid),
    "invalid_rejected":rejected,
    "both_int_subclass_positions_rejected":rejected==len(invalid),
    "model_calls_during_qa":0
},sort_keys=True))
'''


def observed_qa():
    raw=verify_source()
    old_gate.source_bytes("windows_merge")
    earlier=old_gate.independent_qa()["windows_merge"]
    need(earlier.get("int_subclass_rejected") is False
         and earlier.get("int_subclass_actual_if_accepted")=="[(1, 2)]"
         and earlier.get("standard_oracle_passed")==256,
         "PREVIOUS_MODEL_BUG_NOT_REPRODUCIBLE")
    with tempfile.TemporaryDirectory(prefix="vf-office-v2-new-original-v3-") as td:
        p=Path(td)/"windows_merge.py"
        p.write_bytes(raw)
        need(p.read_bytes()==raw,"SOURCE_COPIED_WITH_DIFFERENT_BYTES")
        env={k:os.environ[k] for k in
             ("PATH","SYSTEMROOT","WINDIR","TEMP","TMP","TMPDIR")
             if k in os.environ}
        env["PYTHONDONTWRITEBYTECODE"]="1"
        try:
            result=subprocess.run(
                [sys.executable,"-I","-B","-c",QA_RUNNER,str(p)],
                cwd=td,env=env,capture_output=True,timeout=15,
                text=True,encoding="utf-8",errors="replace")
        except (OSError,subprocess.TimeoutExpired):
            raise Refused("NEW_MODEL_CODE_OFFLINE_QA_UNAVAILABLE")
        need(result.returncode==0 and len(result.stdout)<1500,
             "NEW_MODEL_CODE_QA_PROCESS_FAILED")
        try:
            fresh=json.loads(result.stdout)
        except ValueError:
            raise Refused("NEW_QA_OUTPUT_NOT_JSON")
    return {"previous_exact_model_bug_confirmed":{
                "old_source_sha256":OLD_SOURCE_SHA,
                "old_subclass_rejected":False,
                "old_subclass_actual_if_accepted":"[(1, 2)]"},
            "new_independent_properties":fresh}


def validate(v,qa):
    need(isinstance(v,dict) and v.get("schema")==SCHEMA
         and v.get("status")=="PASS_NEW_FRESH_MODEL_QA_NOT_PRODUCTION_PROMOTION"
         and v.get("issue")=="https://github.com/nocturney/velvetos-core/issues/612",
         "HISTORIC_DATA_STATUS_DRIFT")
    origin=v.get("new_original_worker") or {}
    need(origin.get("task_id")=="p0-diverse-run-mac-merge-exact-int-20261010-d"
         and origin.get("host")=="MacMiniOffice.local"
         and origin.get("base_sha")=="d89317730bc9ff5fac95bd064fea710847e1c404"
         and origin.get("branch")=="lab-p0-diverse-run-p0-diverse-run-mac-merge-exact-int-20261010-d"
         and origin.get("model")=="qwen3.5:4b"
         and origin.get("model_digest")==MODEL_DIGEST
         and origin.get("executed_worker_commit")==
             "e5c9aca933efb99a8f548bed3ed11243ff4f41f7"
         and origin.get("executed_worker_source_sha256")==
             "76dcd612dee33fa4aa01fdc1b73e856100cdf55db94dabb93b7b2a202d0c8c9c"
         and origin.get("prompt_profile")=="PUBLIC_SPEC_EXACT_INT_ENDPOINT_V3"
         and origin.get("prompt_raw_sha256")==
             "34bba908b71e26d6cb12310a4fb5a3fcb07a45e1fc0f8972dc4a4ef787102878"
         and origin.get("envelope_raw_sha256")==
             "dcc9c7eedb55c42028edb435ceb144e592355fa72e1760ba7f9928a8d831b6e1"
         and origin.get("kernel_pin_raw_sha256")==
             "2114d80538c610d6a03f9ab26b5d50062fe2d14c6b94aa0a9f21862d13dc8749"
         and origin.get("model_result_source_sha256")==SOURCE_SHA
         and origin.get("receipt_raw_sha256")==
             "b0cc5ff5e24d33243e65fa7c5f569f7c11bcc275060e76813ed4198e65236fda"
         and origin.get("receipt_selfhash")==
             "fa45eecd4d6bf6cc160eae5350cb9e15ef91735ae4064787e558f9efd491f774"
         and origin.get("original_worker_state")=="SUCCEEDED"
         and origin.get("original_worker_verify")=="PASS"
         and origin.get("original_independent_3_visible") is True
         and origin.get("original_independent_12_hidden") is True
         and origin.get("original_elapsed_seconds")==62.586
         and origin.get("model_invocations_min")==1
         and origin.get("exact_model_call_count") is None
         and origin.get("additional_paid_api_spend_usd")==0
         and origin.get("original_running_journal_cleared_after_success") is True,
         "ORIGINAL_MAC_MODEL_WORKER_OR_RECEIPT_PIN_CHANGED")
    need(v.get("expanded_qa") == qa
         and qa["new_independent_properties"]["standard_oracle_passed"]==256
         and qa["new_independent_properties"]["invalid_rejected"]==11
         and qa["new_independent_properties"]["both_int_subclass_positions_rejected"] is True
         and qa["new_independent_properties"]["model_calls_during_qa"]==0,
         "NEW_MODEL_V3_DID_NOT_PASS_ADDITIONAL_PUBLIC_QA")
    limits=v.get("limits") or {}
    for name in ("old_model_result_rewritten","old_journal_or_receipt_changed",
                 "automatic_retry_of_failed_task","production_code_promoted",
                 "autonomous_code_agent_pr_authored","canonical_fleet_lease",
                 "distributed_fencing_verified","autonomous_unknown_recovery",
                 "two_physical_host_success_newly_proven","model_calls_by_ci",
                 "paid_remote_model_api_calls","secure_os_sandbox_proven"):
        need(limits.get(name) is False,
             "NEW_MODEL_QA_FALSE_AUTHORITY_"+name)
    need(limits.get("new_model_generated_code_quarantined_only") is True
         and limits.get("manual_protected_pr_gate_only") is True,
         "QUARANTINE_SCOPE_REQUIRED")
    return {"status":"PASS_NEW_LOCAL_MODEL_SOURCE_EXACT_BYTES_AND_PUBLIC_PROPERTY_QA",
            "original_worker_verified":True,
            "standard_property_cases":256,
            "invalid_examples_rejected":11,
            "old_bug_still_pinned":True,
            "new_result_quarantined":True,
            "no_autonomous_pr_or_distributed_fence":True,
            "no_new_model_calls_by_verifier":True}


def load_proof():
    need(EVIDENCE.is_file() and not EVIDENCE.is_symlink()
         and EVIDENCE.stat().st_size<18000,"V3_PROOF_NOT_AVAILABLE")
    try:
        return json.loads(EVIDENCE.read_text(encoding="utf-8"))
    except (OSError,ValueError):
        raise Refused("V3_PROOF_PARSE_FAILED")


def selftest(v,qa):
    validate(v,qa)
    cases=["real_historical_and_expanded_oracle_pass"]
    changes=[
        ("false_success",lambda x:x.update(status="PRODUCTION_READY")),
        ("wrong_host",lambda x:x["new_original_worker"].update(host="Chris")),
        ("wrong_task",lambda x:x["new_original_worker"].update(task_id="old-failed-task")),
        ("reuse_old_source",lambda x:x["new_original_worker"].update(model_result_source_sha256=OLD_SOURCE_SHA)),
        ("fake_receipt",lambda x:x["new_original_worker"].update(receipt_raw_sha256="0"*64)),
        ("fake_prompt",lambda x:x["new_original_worker"].update(prompt_profile="ARBITRARY")),
        ("fake_worker",lambda x:x["new_original_worker"].update(executed_worker_source_sha256="0"*64)),
        ("qa_green_false",lambda x:x["expanded_qa"]["new_independent_properties"].update(both_int_subclass_positions_rejected=False)),
        ("tamper_property",lambda x:x["expanded_qa"]["new_independent_properties"].update(invalid_rejected=1)),
        ("hide_old_bug",lambda x:x["expanded_qa"]["previous_exact_model_bug_confirmed"].update(old_subclass_rejected=True)),
        ("false_auto_retry",lambda x:x["limits"].update(automatic_retry_of_failed_task=True)),
        ("false_prod",lambda x:x["limits"].update(production_code_promoted=True)),
        ("false_pr_agent",lambda x:x["limits"].update(autonomous_code_agent_pr_authored=True)),
        ("false_distributed_fence",lambda x:x["limits"].update(distributed_fencing_verified=True)),
        ("false_os_sandbox",lambda x:x["limits"].update(secure_os_sandbox_proven=True)),
        ("paid_api",lambda x:x["limits"].update(paid_remote_model_api_calls=True)),
    ]
    for label,change in changes:
        attempt=copy.deepcopy(v)
        change(attempt)
        try:
            validate(attempt,qa)
        except Refused:
            cases.append(label+"_DENIED")
        else:
            raise AssertionError("FALSE_GREEN_MODEL_RESULT_ACCEPTED_"+label)
    with tempfile.TemporaryDirectory(prefix="vf-office-v2-bad-model-source-") as td:
        changed=Path(td)/"windows_merge_exact_int_v3.py"
        changed.write_bytes(verify_source()+b"\n#tampered\n")
        try:
            verify_source(changed)
        except Refused:
            cases.append("changed_exact_source_DENIED")
        else:
            raise AssertionError("CHANGED_MODEL_SOURCE_ACCEPTED")
    need(len(cases)==18,"SOURCE_V3_NEGATIVE_COUNT_DRIFT")
    return {"status":"PASS_OFFLINE","tests":len(cases),
            "model_calls":0,"production_code_promoted":False,
            "cross_host_fencing":False}


def main():
    p=argparse.ArgumentParser()
    p.add_argument("mode",choices=("probe","verify","selftest"))
    a=p.parse_args()
    qa=observed_qa()
    if a.mode=="probe":
        result={"status":"ORIGINAL_TWO_CODE_VERSION_QA_COMPARISON_OFFLINE",
                "observed":qa,"no_model_calls":True}
    else:
        proof=load_proof()
        result=validate(proof,qa) if a.mode=="verify" else selftest(proof,qa)
    print(json.dumps(result,sort_keys=True))


if __name__=="__main__":
    try: main()
    except (Refused,AssertionError,OSError,KeyError,ValueError,TypeError) as e:
        print(json.dumps({"status":"FAIL_CLOSED","reason":str(e)[:180],
                          "model_calls":0,"production_effects":0},sort_keys=True))
        raise SystemExit(2)
